### ISSUE TITLE
Feedback on page: src/support-tools/patches-available-in-qpt-tool/mdva-34330-orders-are-not-filtered-according-to-admin-timezone.md

### ISSUE THREAD

**Issue by atIOCrON** [magento/knowledge-base#109]
### Article URL

https://support.magento.com/hc/en-us/articles/4403024155917-MDVA-34330-Orders-not-filtered-according-to-admin-timezone

### Description

The article says:

"Please note that the issue is scheduled to be fixed in Adobe Commerce 2.4.3."

However, we're running 2.4.3-p1 and this issue still persists.

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by almarchenko** [comment]
Hey @atIOCrON, I'll check with developers team

**Comment by almarchenko** [comment]
Hey @atIOCrON , our developers confirm that 2.4.3 contains this fix.
If the issue persists, please [create a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket) (if you are a Commerce customer) or report the issue here, if you are on Open Source https://github.com/magento/magento2/issues.
