### ISSUE TITLE
Feedback on page: src/how-to/general/mbi-pro-demo.md

### ISSUE THREAD

**Issue by Siftah** [magento/knowledge-base#132]
### Article URL

https://support.magento.com/hc/en-us/articles/360016729571

### Description

Video doesn't work, gives error message:
"Cannot load video.
This video is unavailable."

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanay-sharma** [comment]
Hey @Siftah, thank you for the submission! We have created a ticket for it: https://jira.corp.adobe.com/browse/MSKB-1482

**Comment by almarchenko** [comment]
Hey @Siftah  thank you for letting us know. Here's the latest development with the MBI video articles in our KB:
We had to remove the following articles, since the video tutorial files stopped being available:

MBI Pro Getting Started Video Series
MBI Training Video Show Top-Bottom and Independent Group By Features
MBI Training Video Time Options in the Visual Report Builder
MBI Webinar Archives
MBI Pro Demo
Those MBI video tutorials, that are still available, are now published in the [Commerce Videos and Tutorials section](https://experienceleague.adobe.com/docs/commerce-learn/tutorials/overview.html?lang=en) on the Adobe Commerce Experience League site.
